### ISSUE TITLE
Build example failed

### ISSUE THREAD

**Issue by jiewang416** [fnproject/flow-lib-go#14]
# Error output
Step 6/10 : RUN cd /go/src/func/ && go build -o func
 ---> Running in 0dc0f0ce1e73
func/vendor/github.com/fnproject/flow-lib-go
vendor/github.com/fnproject/flow-lib-go/codecs.go:37:20: cannot convert c.ctx (type context.Context) to type fdk.Context:
	context.Context does not implement fdk.Context (missing AppID method)
vendor/github.com/fnproject/flow-lib-go/codecs.go:37:34: invalid operation: fdk.Context(c.ctx).Config[appName] (type func() map[string]string does not support indexing)
vendor/github.com/fnproject/flow-lib-go/codecs.go:41:20: cannot convert c.ctx (type context.Context) to type fdk.Context:
	context.Context does not implement fdk.Context (missing AppID method)
vendor/github.com/fnproject/flow-lib-go/codecs.go:41:34: invalid operation: fdk.Context(c.ctx).Config[fnID] (type func() map[string]string does not support indexing)
vendor/github.com/fnproject/flow-lib-go/codecs.go:61:18: cannot convert c.ctx (type context.Context) to type fdk.Context:
	context.Context does not implement fdk.Context (missing AppID method)
vendor/github.com/fnproject/flow-lib-go/codecs.go:61:32: fdk.Context(c.ctx).Header.Get undefined (type func() http.Header has no field or method Get)

# Triage

fdk-go has changed Context from a function to a interface.
https://github.com/fnproject/fdk-go/blob/master/fdk.go:
// Context contains all configuration for a function invocation
type Context interface {

But flow-lib-go is not updated accordingly.

**Comment by denismakogon** [comment]
FDK contract changed, not sure if this example is up to date, actually.

**Comment by rdallman** [comment]
thanks - this should be a quick update
