### ISSUE TITLE
Flow continuation fails when combining fdk handler to accept http input to function

### ISSUE THREAD

**Issue by defucius** [fnproject/flow-lib-go#4]
With the provided flow example, add code from the fdk boiler plate to accept http input to the function as in the attached file. The stage continuation fails with the following output:

Enabled debugging
Awakened flow 26607dbd-66be-4eab-a2af-f09c43b43904
Handling continuation
panic: Failed to decode stage invocation request: EOF

goroutine 1 [running]:
func/vendor/github.com/fnproject/flow-lib-go.handleInvocation(0x8e79e0, 0xc42031cbe0)
	/go/src/func/vendor/github.com/fnproject/flow-lib-go/invocations.go:86 +0x1ab
func/vendor/github.com/fnproject/flow-lib-go.WithFlow(0x8af880)
	/go/src/func/vendor/github.com/fnproject/flow-lib-go/flows.go:108 +0x126
main.stringExample()
	/go/src/func/func.go:58 +0x2d
main.myHandler(0x8e73a0, 0xc420070600, 0x8e3e60, 0xc42000e010, 0x8e3e80, 0xc42000e018)
	/go/src/func/func.go:51 +0xcb
func/vendor/github.com/fnproject/fdk-go.HandlerFunc.Serve(0x8af878, 0x8e73a0, 0xc420070600, 0x8e3e60, 0xc42000e010, 0x8e3e80, 0xc42000e018)
	/go/src/func/vendor/github.com/fnproject/fdk-go/fdk.go:19 +0x62
func/vendor/github.com/fnproject/fdk-go/utils.DoDefault(0x7f1e08c827c0, 0x8af878, 0x8e73a0, 0xc420070600, 0x8e3e60, 0xc42000e010, 0x8e3e80, 0xc42000e018)
	/go/src/func/vendor/github.com/fnproject/fdk-go/utils/utils.go:63 +0xf9
func/vendor/github.com/fnproject/fdk-go/utils.Do(0x7f1e08c827c0, 0x8af878, 0xc4200240aa, 0x7, 0x8e3e60, 0xc42000e010, 0x8e3e80, 0xc42000e018)
	/go/src/func/vendor/github.com/fnproject/fdk-go/utils/utils.go:49 +0x251
func/vendor/github.com/fnproject/fdk-go.Handle(0x8e4380, 0x8af878)
	/go/src/func/vendor/github.com/fnproject/fdk-go/fdk.go:81 +0xce
main.main()
	/go/src/func/func.go:31 +0x39

[func.go.zip](https://github.com/fnproject/flow-lib-go/files/1991943/func.go.zip)

**Comment by gviedma** [comment]
There are a couple of reasons your example is failing:

1. The complete flow-based program needs to be enclosed within a `flows.WithFlow` block.  If you consume input or produce function output outside the block, things will break.
2. By calling _printResult_ you are writing to the function's output. However, you later try to serialize a struct to json to stdout as well, so you have a mix of logging output and json. I doubt that is what you want.

Here is a snippet which does what I believe you want:
```golang
func myHandler(ctx context.Context, in io.Reader, out io.Writer) {
	flows.WithFlow(
		func() {
			p := &Person{Name: "World"}
			json.NewDecoder(in).Decode(p)
                          // use the name passed in as input to the function as initial flow stage
			cf := flows.CurrentFlow().CompletedValue(p.Name)
			valueCh, errorCh := cf.ThenApply(strings.ToUpper).ThenApply(strings.ToLower).Get()
			select {
			case value := <-valueCh:
                                   // output the result of the flow transformation as the result of this function
				p.Name = value.(string)
				json.NewEncoder(out).Encode(p)
			case err := <-errorCh:
				io.WriteString(out, fmt.Sprintf(`{"error":"Flow failed with error %v}`, err))
			case <-time.After(time.Minute * 1):
				io.WriteString(out, `{"error":"Flow timed out}`)
			}
		})
}
```
